.gitignore, docs/testcases/global_variables.md, example/hello.nf.test, mkdocs.yml, src/main/java/com/askimed/nf/test/lang/ParamsMap.java, src/main/java/com/askimed/nf/test/lang/TestContext.java, src/main/java/com/askimed/nf/test/lang/extensions/PathExtension.java, src/main/java/com/askimed/nf/test/lang/function/FunctionTest.java, src/main/java/com/askimed/nf/test/lang/pipeline/PipelineTest.java, src/main/java/com/askimed/nf/test/lang/process/ProcessTest.java, src/main/java/com/askimed/nf/test/lang/workflow/WorkflowTest.java, src/test/java/com/askimed/nf/test/lang/NextflowTestSuiteBuilderTest.java, src/test/java/com/askimed/nf/test/lang/ProcessTest.java, test-data/pipeline/dsl1/params.json, test-data/pipeline/dsl1/params.yml, test-data/pipeline/dsl1/test1.nf.test, test-data/process/nested-params/params.json, test-data/process/nested-params/params.yaml, test-data/process/nested-params/process.nf, test-data/process/nested-params/process.nf.test
=> Nested params and json/yaml files

README.md, docs/assertions/assertions.md, example/hello.nf.test, src/main/java/com/askimed/nf/test/lang/extensions/GlobalMethods.java, src/test/java/com/askimed/nf/test/lang/extensions/GlobalMethodsTest.java, test-data/assertAll.groovy
An `assertAll` method. Like JUnit's assertAll but for groovy closures:
- added link to full documentation at the top of the readme
- Updated `assertions.md` with info on how to use
- Added an `assertAll` method to GlobalMethods
- Added a unit test for `assertAll`
Fixes: https://github.com/askimed/nf-test/issues/43
=> Assert all

docs/assertions/files.md
this is the only way this worked for me, so i think maybe adding the parentheses to the size method(?) are needed, but i'm new to this language though so i apologize if not!
=> small code typo in the GZip files example (i think)

docs/configuration.md, docs/getting-started.md, src/main/java/com/askimed/nf/test/commands/RunTestsCommand.java, src/main/java/com/askimed/nf/test/config/Config.java, src/main/java/com/askimed/nf/test/core/AbstractTest.java, src/main/java/com/askimed/nf/test/core/AbstractTestSuite.java, src/main/java/com/askimed/nf/test/core/ITaggable.java, src/main/java/com/askimed/nf/test/core/ITest.java, src/main/java/com/askimed/nf/test/core/ITestSuite.java, src/main/java/com/askimed/nf/test/core/TagQuery.java, src/main/java/com/askimed/nf/test/core/TestExecutionEngine.java, src/main/java/com/askimed/nf/test/lang/function/FunctionTest.java, src/main/java/com/askimed/nf/test/lang/pipeline/PipelineTest.java, src/main/java/com/askimed/nf/test/lang/process/ProcessTest.java, src/main/java/com/askimed/nf/test/lang/workflow/WorkflowTest.java, src/main/java/com/askimed/nf/test/nextflow/NextflowCommand.java, src/main/java/com/askimed/nf/test/nextflow/NextflowLog.java, src/main/java/com/askimed/nf/test/nextflow/NextflowLogLevel.java, src/test/java/com/askimed/nf/test/core/TestExecutionEngineTest.java, src/test/java/com/askimed/nf/test/nextflow/NextflowCommandTest.java, test-data/suite1.nf.test, test-data/suite2.nf.test
This PR adds the possibility to set additional nextflow options. This should fix #71 and #73.
It is possible to set and overwrite options on different levels:
In `nf-test.config`:
```
config {
options "-dump-channels -stub-run"
}
```
For a testsuite:
```
nextflow_process {
options "-dump-channels"
}
```
Or for a test:
```
test("Should create 5 files") {
options "-dump-channels"
}
```
By default, all Nextflow output (e.g. println, dump-channels)  or error messages  are written to `.nf-test/<work-dir>/meta/std.*`. Set the nf-test `--debug` option, to output everything on the command-line. 
What do you think? @ewels @matthdsm
=> Add `options` keyword to set specific Nextflow options

.gitignore, example/hello.nf.test.snap, pom.xml, src/main/java/com/askimed/nf/test/App.java, src/main/java/com/askimed/nf/test/commands/AbstractCommand.java, src/main/java/com/askimed/nf/test/commands/RunTestsCommand.java, src/main/java/com/askimed/nf/test/core/AbstractTest.java, src/main/java/com/askimed/nf/test/core/AbstractTestSuite.java, src/main/java/com/askimed/nf/test/core/TestExecutionEngine.java, src/main/java/com/askimed/nf/test/lang/extensions/Snapshot.java, src/main/java/com/askimed/nf/test/lang/extensions/SnapshotFile.java, src/main/java/com/askimed/nf/test/util/LoggerUtil.java
This PR fixes #95 and writes a log file `.nf-test.log` to the current directory. The filename of the log-file can be customised with `--log my-log-file.log`.
=> Add basic logging support

docs/docs/cli/test.md, docs/docs/configuration.md, src/main/java/com/askimed/nf/test/commands/RunTestsCommand.java, src/main/java/com/askimed/nf/test/core/AbstractTestSuite.java, src/main/java/com/askimed/nf/test/core/ITestSuite.java, src/main/java/com/askimed/nf/test/core/TestExecutionEngine.java, src/main/java/com/askimed/nf/test/lang/function/FunctionTest.java, src/main/java/com/askimed/nf/test/lang/pipeline/PipelineTest.java, src/main/java/com/askimed/nf/test/lang/process/ProcessTest.java, src/main/java/com/askimed/nf/test/lang/workflow/WorkflowTest.java, src/main/java/com/askimed/nf/test/nextflow/NextflowCommand.java, src/test/java/com/askimed/nf/test/lang/ProcessTest.java, test-data/process/profiles/hello.a.nf.test, test-data/process/profiles/hello.b.nf.test, test-data/process/profiles/hello.c.nf.test, test-data/process/profiles/hello.nf, test-data/process/profiles/nextflow.config, test-data/process/profiles/nf-test.config
This PR fixes #94.
By default, `nf-test` reads the profile configuration from `nf-test.config`. If you've defined a profile called `A` in `nf-test.config`, running `nf-test --profile B` will start Nextflow with only the `B` profile. It replaces any existing profiles.
To combine profiles, you can use the `+` prefix. For example, running `nf-test --profile +B` will start Nextflow with both `A` and `B` profiles, resulting in `-profile A,B`. This allows you to extend the existing configuration with additional profiles.
Profiles are evaluated in a specific order, ensuring predictable behavior:
1. **Profile in nf-test.config:** The first profile considered is the one defined in `nf-test.config`.
2. **Profile Defined in Testcase:** If you specify a profile within a testcase, it takes precedence …
=> Add possibility to set and combine multiple profiles

docs/docs/configuration.md, src/main/java/com/askimed/nf/test/commands/RunTestsCommand.java, src/main/java/com/askimed/nf/test/config/Config.java, src/main/java/com/askimed/nf/test/config/FileStaging.java, src/main/java/com/askimed/nf/test/config/StageBuilder.java, src/main/java/com/askimed/nf/test/core/AbstractTest.java, src/main/java/com/askimed/nf/test/core/AbstractTestSuite.java, src/main/java/com/askimed/nf/test/core/ITest.java, src/test/java/com/askimed/nf/test/lang/WorkflowTest.java, test-assets/test.txt, test-data/workflow/staging/hello-stage.nf.test, test-data/workflow/staging/hello.nf, test-data/workflow/staging/hello.nf.test, test-data/workflow/staging/nf-test.file.config, test-data/workflow/staging/nf-test.file.mode.config, test-data/workflow/staging/nf-test.folder.config
This PR fixes #99 by adding the `stage` section to `nf-test.config`. The `stage` section  is used to define files that are needed by Nextflow in the test environment (`meta` directory). Additionally, the directories `lib`, `bin`, and `assets` are automatically staged.
Here's an example of how to use the `stage` section in an `nf-test.config` file:
```groovy
config {
...
stage {
symlink "data/original_data.txt"
copy "resources/config.yml"
}
...
}
```
In this example:
- The `symlink` directive creates a symlink named "data/original_data.txt" in the `meta` directory pointing to the file located at "data/original_data.txt."
- The `copy` directive copies the "config.yml" file from the "resources" directory to the `meta/resources` directory.
Furthermore, it is also possible to stage files that …
=> Add option for staging user-defined files

docs/docs/testcases/setup.md, mkdocs.yml, src/main/java/com/askimed/nf/test/core/AbstractTest.java, src/main/java/com/askimed/nf/test/core/AbstractTestSuite.java, src/main/java/com/askimed/nf/test/lang/Dependency.java, src/main/java/com/askimed/nf/test/lang/process/ProcessContext.java, src/main/java/com/askimed/nf/test/lang/process/ProcessTest.java, src/main/java/com/askimed/nf/test/lang/process/ProcessTestSuite.java, src/main/java/com/askimed/nf/test/lang/workflow/WorkflowContext.java, src/main/java/com/askimed/nf/test/lang/workflow/WorkflowTest.java, src/main/java/com/askimed/nf/test/lang/workflow/WorkflowTestSuite.java, src/main/java/com/askimed/nf/test/util/Command.java, src/main/resources/com/askimed/nf/test/lang/process/WorkflowMock.nf, src/main/resources/com/askimed/nf/test/lang/workflow/WorkflowMock.nf, src/test/java/com/askimed/nf/test/lang/ProcessTest.java, test-data/process/abricate/run/main.nf, test-data/process/abricate/summary/main.nf, test-data/process/abricate/summary/tests/main.nf.test, test-data/process/abricate/summary/tests/main.nf.test.snap, test-data/process/abricate/summary/tests/nextflow.config, test-data/process/dependencies/generate_data.nf, test-data/process/dependencies/process_data.nf, test-data/process/dependencies/process_data.nf.test, test-data/process/dependencies/process_data.nf.test.snap
This pull  PR enables the execution of dependent modules for generating test data (Fixes #70).
With these changes, it is now possible to specify processes in the setup method that need to be executed before the `when` block. The outputs of these processes can then be utilized to define parameters or map processes/workflows. The `run`method takes the processs or workflow name, the (relativ) path to the script file and the input mapping as arguments.
For example, the following testcase for the `ABRICATE_SUMMARY` module executes the `ABRICATE_RUN` module to generate the input data:
```
nextflow_process {
name "Test process data"
script "../main.nf"
process "ABRICATE_SUMMARY"
config "./nextflow.config"
test("Should use process ABRICATE_RUN to generate input data") {
setup { …
```
=> Enable the execution of dependent modules for generating test data

src/main/java/com/askimed/nf/test/commands/InitCommand.java
Makes sure creating the default NextFlow config is skipped if it already exists, instead of only printing the message to skip it.
=> Actually skip creating default NextflowConfig

docs/docs/assertions/files.md, src/main/java/com/askimed/nf/test/util/FileUtil.java
This  PR changes the way that md5 hashes are calculated from gzip files as described in #141. In short: for `.gz` files only, the md5 hash is now calculated on the decompressed file contents, equivalent to:
```bash
gunzip -c file.gz | md5sum
```
As mentioned in the issue, this will break previously defined assertions/snapshots on gzip files
=> calculate md5 hash of .gz files based on file content

docs/docs/assertions/snapshots.md
Might not be the cleanest example, but it's something that tripped me up (and possibly others at nf-core) when looking at the docs - as in I wasn't sure exactly what the scope of an 'object' was.
I know that there is a dedicated 'file paths' section, but I feel having a specific example of a file snapshot in the 'landing page' of the Snapshot page might be useful as it is a  very common check (i.e., has the file contents changed between runs?).
Feel free to change the example to a simpler one if you wish.
=> docs: add explicit file snapshot example

src/main/java/com/askimed/nf/test/util/CommandStreamHandler.java, src/test/java/com/askimed/nf/test/util/CommandStreamHandlerTest.java
Add a `CommandStreamHandler` test case that demonstrates current improper handling, and add logic to fix it by splitting on lines. Fixes https://github.com/askimed/nf-test/issues/166
There is an example of a failing test case demonstrating the issue on my fork [here](https://github.com/ahvigil/nf-test/actions/runs/7282081625/job/19843802984) which gets [resolved](https://github.com/ahvigil/nf-test/actions/runs/7282084885/job/19843812182) with this change.
```
Error:  Failures: 
Error:    CommandStreamHandlerTest.testCommandStreamHandler:53 expected: <    > ------------------------------------------------------
> If you use nf-core/rnaseq for your analysis please cite:
> 
> * The pipeline
>   https://doi.org/10.5281/zenodo.1400710
> 
> * The nf-core framework
> …
```
=> split on lines in CommandStreamHandler

src/main/java/com/askimed/nf/test/config/Config.java, src/main/java/com/askimed/nf/test/core/AbstractTest.java
This PR sets the default file-staging mode to `copy` and adds a property to the config file to change it.
It could be changed to symlink with:
```
config {
stageMode "symlink"
}
```
This should help to investigate and understand issue #149
=> Set default staging mode in config file

.github/workflows/run-tests.yml, docs/CNAME, pom.xml, src/main/java/com/askimed/nf/test/App.java, src/main/java/com/askimed/nf/test/config/Config.java, src/main/java/com/askimed/nf/test/core/AbstractTest.java
This PR adds a matrix to test all combinations with Java 11, 17 and 21 and Nextflow latest-stable and latest-edge.
=> Update test strategy in github actions

src/main/java/com/askimed/nf/test/core/TestExecutionEngine.java, src/main/java/com/askimed/nf/test/util/OutputFormat.java
This PR adds `--format csv` to the list commands. Fixes #177
=> Add csv format to `list` commands

src/main/java/com/askimed/nf/test/lang/extensions/Snapshot.java, src/test/java/com/askimed/nf/test/lang/ProcessTest.java, test-data/process/snapshots/no-unique.test, test-data/process/snapshots/process.nf, test-data/process/snapshots/unique.nf.test, test-data/process/snapshots/unique.nf.test.snap
Throws an error when a user creates more than one unnamed snapshot or mutiple snapshots with the same id to avoid unexpected snapshot matching. Fixes #158
=> Throw error when a snapshot with same id was created multiple time

src/main/java/com/askimed/nf/test/commands/AbstractCommand.java, src/main/java/com/askimed/nf/test/lang/extensions/SnapshotFile.java, src/main/java/com/askimed/nf/test/lang/extensions/SnapshotFileItem.java, src/main/java/com/askimed/nf/test/nextflow/NextflowCommand.java, src/main/java/com/askimed/nf/test/util/Command.java, src/main/java/com/askimed/nf/test/util/CommandStreamHandler.java
This PR adds a property `meta` to a snapshot containing the versions used to create it. Fixes #170 
Example:
```
"Should succeed ....": {
"content": [
[
"output.txt:md5,286d2f149346ef78d42276aaf0f32693"
]
],
"meta": {
"nf-test": "0.8.3",
"nextflow": "23.04.3"
},
"timestamp": "2024-01-27T14:24:56.05131"
}
```
=> Add nf-test and nextflow version to snapshots

src/main/resources/com/askimed/nf/test/lang/function/WorkflowMock.nf, src/main/resources/com/askimed/nf/test/lang/process/WorkflowMock.nf, src/main/resources/com/askimed/nf/test/lang/workflow/WorkflowMock.nf
This PR writes always the absolute path to the channel's json file to ensure that snapshots are able to pick up files. This fixes #173
=> Fix issue with relative paths in channel serialization

docs/docs/assertions/snapshots.md, src/main/java/com/askimed/nf/test/lang/extensions/Snapshot.java, src/main/java/com/askimed/nf/test/lang/extensions/SnapshotFileItem.java, src/main/java/com/askimed/nf/test/util/ObjectUtil.java, src/test/java/com/askimed/nf/test/lang/ProcessTest.java, test-data/process/snapshots/md5.nf.test, test-data/process/snapshots/md5.nf.test.snap
This PR adds the function `md5()` to snapshots that allow to store the hashsum instead of the content in the snapshot file. This fixes #175.
```
def content = [
object1: "lukas",
object2: 27,
object3: [
a: "lll",
b: [1,2,3,4,5,6]
]
]
assert snapshot(content).match("snapshot1")
assert snapshot(content).md5().match("snapshot2")
```
Snapshot:
```
{
"snapshot1": {
"content": [
{
"object1": "lukas",
"object2": 27,
"object3": {
"a": "lll",
"b": [
1,
2,
3,
4,
5,
6
]
}
}
],
"timestamp": "2024-01-28T11:41:29.018819"
},
"snapshot2": {
"content": "a54d97026c5ed6e6a57ccd3a3f5a3cbc",
"timestamp": "2024-01-28T11:41:29.025981"
}
}
```
=> Add `md5()` function to snapshot

docs/docs/testcases/setup.md, src/main/java/com/askimed/nf/test/lang/Dependency.java, src/main/java/com/askimed/nf/test/lang/process/ProcessContext.java, src/main/java/com/askimed/nf/test/lang/workflow/WorkflowContext.java, src/main/resources/com/askimed/nf/test/lang/process/WorkflowMock.nf, src/main/resources/com/askimed/nf/test/lang/workflow/WorkflowMock.nf, src/test/java/com/askimed/nf/test/lang/ProcessTest.java, test-data/process/dependencies/process_data_alias.nf.test
This PR adds the parameter `alias` to the run method to define the alias for dependencies. This address issue #139 
Example:
```
run("GENERATE_DATA", alias: "LUKAS") {
script "./generate_data.nf"
process {
"""
input[0] = "nf-core"
"""
}
}
```
=> Add property to set alias for dependencies

src/main/java/com/askimed/nf/test/core/AbstractTest.java, src/main/java/com/askimed/nf/test/core/AbstractTestSuite.java, src/main/java/com/askimed/nf/test/core/ITest.java, src/main/java/com/askimed/nf/test/core/ITestSuite.java, src/main/java/com/askimed/nf/test/core/TestExecutionEngine.java
This change separates the definition of the launch/meta/output/work directory paths from the physical re-initialization of the actual directories on the filesystem. The definition of the paths still happens up front, but the init and the rest of the `setup()` call has been moved down into the test execution engine inner loop. This prevents nf-test from changing the filesystem until the last moment before any given test actually runs. With this change, `nf-test list` or running specified tests no longer deletes the output from other tests. This also conveniently enables running tests in parallel without any extra filesystem isolation or containerization.
Fixes #213
=> Delay launchdir init until test execution

src/main/java/com/askimed/nf/test/core/AbstractTest.java, src/main/java/com/askimed/nf/test/lang/function/FunctionTest.java, src/main/java/com/askimed/nf/test/lang/process/ProcessTest.java, src/main/java/com/askimed/nf/test/lang/workflow/WorkflowTest.java, src/main/java/com/askimed/nf/test/util/FileUtil.java, src/main/java/com/askimed/nf/test/util/HashUtil.java, src/test/java/com/askimed/nf/test/lang/WorkflowTest.java, test-data/workflow/regex/params.yaml, test-data/workflow/regex/workflow.nf, test-data/workflow/regex/workflow.nf.test
This PR introduces the creation of the `mock.nf` file in the project folder (instead of the `meta` folder) to preserve Nextflow's `projectDir`. The mock file has a unique name (`.nf-test-${test-hash}.nf`) and after execution, the file is moved to the `meta` folder for debugging purposes. Consequently, there's no longer a need to stage files to the meta directory.
This PR addresses the following issues:
- Automatic staging of assets bin and lib folders is broken (see: https://github.com/askimed/nf-test/issues/193).
- projectDir references become invalid under nf-test (see: https://github.com/askimed/nf-test/issues/99#issuecomment-1912915028).
Additionally, this change could resolve the issue:
- Process relative paths aren't resolved correctly (see: …
=> Create `mock.nf` in project folder instead of meta folder

docs/docs/cli/test.md, src/main/java/com/askimed/nf/test/commands/RunTestsCommand.java, src/main/java/com/askimed/nf/test/core/AbstractTest.java, src/main/java/com/askimed/nf/test/core/ITest.java, src/main/java/com/askimed/nf/test/core/TestExecutionEngine.java, src/main/java/com/askimed/nf/test/lang/extensions/Snapshot.java
The `--ci` flag activates the CI mode. Instead of automatically storing a new snapshot as per usual, it will now fail the test if no reference snapshot is available.
his enables tests to fail on GitHub actions when a snapshot file was forgotten to be committed.
=> Add `--ci` flag

.gitignore, docs/docs/cli/test.md, docs/tutorials/github-actions.md, src/main/java/com/askimed/nf/test/commands/RunTestsCommand.java, src/main/java/com/askimed/nf/test/lang/dependencies/DependencyGraph.java, src/main/java/com/askimed/nf/test/lang/dependencies/DependencyResolver.java, src/main/java/com/askimed/nf/test/lang/dependencies/IMetaFile.java, src/main/java/com/askimed/nf/test/lang/dependencies/SnapshotFile.java, src/main/java/com/askimed/nf/test/lang/dependencies/TestFile.java, src/main/java/com/askimed/nf/test/nextflow/NextflowScript.java, src/test/java/com/askimed/nf/test/lang/dependencies/DependencyResolverTest.java, src/test/java/com/askimed/nf/test/lang/dependencies/IMetaFileTest.java
This PR add the `--filter` flag to filter test cases and dependencies based on the type (e.g. workflow,process,pipeline or function). This addresses #196.
=> Add flag to filter dependencies based on test case type

src/main/java/com/askimed/nf/test/core/reports/XmlReportWriter.java
This adds the `classname` attribute to the `testcase` elements in the junit xml report. 
Closes #228
=> feat: add classname attribute to junit xml report

src/main/resources/com/askimed/nf/test/lang/function/WorkflowMock.nf, src/main/resources/com/askimed/nf/test/lang/process/WorkflowMock.nf, src/main/resources/com/askimed/nf/test/lang/workflow/WorkflowMock.nf, src/test/java/com/askimed/nf/test/lang/ProcessTest.java, test-data/channels/null-values/return_null.nf, test-data/channels/null-values/return_null.nf.test
This PR ensures that null values are included when serializing data in channel outputs.
Fixes #226
=> Serializes null values in channel outputs

src/main/java/com/askimed/nf/test/core/TestSuiteResolver.java
Fixes #263.
The `TestSuiteResolver.parse` method fails when an "@" symbol is in the path. This is because it splits the script's path on "@" to retrieve test ID without accounting for other "@" symbols elsewhere in the path. I have fixed this by using `java.nio.file.Paths` to split the file name from the base path and check only the file name for an "@" symbol.
Let me know if the addition of a unit test case for this would be useful (e.g. to test the case where `scripts` contains a path with an "@" symbol).
=> Fix TestSuiteResolver parse path containing "@" symbol

docs/resources.md
Smallest of PRs just fixing the link to the hello nf-test training since this is now under 08_*.
=> Fix hello nf-test training link

docs/docs/testcases/global_variables.md
As mentioned on Slack, turns out `moduleDir` also applies to subworkflows, so this PR changes the docs to reflect that. Tried to make a newline in the table with `\\`, not sure if it worked.
=> Suggest update to `moduleDir` docs to include subworkflow dir

docs/docs/cli/test.md, docs/tutorials/github-actions.md, src/main/java/com/askimed/nf/test/commands/RunTestsCommand.java
Currently the documentation lists `module` as a valid option for the `--filter` flag but that is not recognized. From the code it seems that `process` should be used instead. This PR just fixes up the docs by replacing `module` with `process`.
=> Fix documentation for `--filter` using `module` instead of `process`
